### ISSUE TITLE
Add bwateratmsft to the repo

### ISSUE THREAD

**Issue by karolz-ms** [docker-archive-public/docker.node-sdk-legacy#16]
@rumpl  or @chris-crone , could we add @bwateratmsft to the repo? 

He will be working with me on the SDK adoption in VS Code Docker extension codebase.

Thx!
Karol

**Comment by rumpl** [comment]
@karolz-ms just added Brandon to the repo

@bwateratmsft welcome :)

**Comment by bwateratmsft** [comment]
@rumpl Thanks!
