### ISSUE TITLE
Additional APIs

### ISSUE THREAD

**Issue by bwateratmsft** [docker-archive-public/docker.node-sdk-legacy#17]
Some additional APIs that would be nice to have for our July release:

- [x] OS type on the List API?
- [x] Start / restart container
- [x] Stop container
- [x] OS type on the Inspect API
- [x] Inspect container

**Comment by rumpl** [comment]
Hey @bwateratmsft 

1. you can start a container with the `Run` method but I have a feeling that's not what you mean
2. we linked the `stop container` to the `Delete` method, we will have to change it to be on the `Stop` method
3. `Inspect` is coming, will update here when it's available

**Comment by bwateratmsft** [comment]
> 1. you can start a container with the `Run` method but I have a feeling that's not what you mean

The "start" I was thinking was to start an already-existing-but-stopped container, basically equivalent to this button:
![image](https://user-images.githubusercontent.com/36966225/86148641-e36cb800-bac8-11ea-9c0b-a6e4c0f76937.png)

I tried `Run` with the container's name as the ID, but it errored saying that a container group of that name already existed. I assume `Run` in means "Run a new container".

Similarly, `Stop` I'm hoping would just be the equivalent to that "Stop" button, but would not delete anything. "Restart" is [defined on the ACI API](https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/restart) but as far as I know it is no different than doing Stop + Start, so if it wasn't added to this SDK we could still implement it easily.

**Comment by karolz-ms** [comment]
@bwateratmsft @rumpl there are some design issues with start/stop semantics with ACI https://github.com/docker/desktop-microsoft/issues/24

That said, we will still need start/stop/restart support in the SDK, for traditional Docker engine and other backends

**Comment by bwateratmsft** [comment]
Updated the initial comment to make it a checklist and also add an item (OS type, i.e. Windows vs. Linux)

**Comment by gtardif** [comment]
OS type on the Inspect API should be good with last shared binary. (feel free to uncheck the box if you see issues)
Actually I missed `is in the CLI result but not in the SDK yet`... so unchecked the box

**Comment by bwateratmsft** [comment]
Yes, the OS type is on the CLI output for sure but didn't make it to the SDK. :smile:

Right now our only use case for the platform is in deciding whether to use "cmd" or an over-complicated shell script that picks between bash and sh, when doing `docker exec -it` to attach. Absent knowing the platform we just assume it's Linux, which is correct the majority of the time.

**Comment by bwateratmsft** [comment]
Validated that Stop / Start now work.

@rumpl I saw you added `platform` to the Containers proto, but it is always returning empty string--is this known?

EDIT: it *does* show the platform on `inspect`, just not on `list`. This is sufficient for our purposes, but want to double-check if you also want it showing on `list`.

**Comment by rumpl** [comment]
@bwateratmsft I just tested with the `examples/ps.ts` and it would seem we are returning the platform on list:

```typescript
import * as grpc from '@grpc/grpc-js';

import { Containers } from '../src/index';
import { ListRequest, ListResponse } from '../src/containers';

const client = new Containers('unix:///tmp/backend.sock');
client.list(
  new ListRequest(),
  (error: grpc.ServiceError | null, response: ListResponse) => {
    if (error != null) {
      throw error;
    }
    const containers = response.getContainersList();
    containers.forEach((container) => {
      console.log(
        container.getId(),
        container.getImage(),
        container.getStatus(),
        // Added this line
        container.getPlatform()
      );
    });
  }
);
```

```shell
$ yarn run example examples/ps.ts
yarn run v1.22.4
$ ts-node examples/ps.ts
adoring-pasteur nginx Running Linux
```

**Comment by bwateratmsft** [comment]
@rumpl Maybe the issue only affects ACI containers?

**Comment by rumpl** [comment]
Ok I just tested with the gRPC server from edge, the platform is indeed not there, this is something that we fixed in the meantime then and will be available soon :)

**Comment by bwateratmsft** [comment]
Verified that this is working now. All of the original list are fixed now, thanks!
