### ISSUE TITLE
Equivalent to `--context` / `DOCKER_CONTEXT` for SDK

### ISSUE THREAD

**Issue by bwateratmsft** [docker-archive-public/docker.node-sdk-legacy#42]
The CLI has a `--context` flag that allows you to specify a context to use without necessarily changing to that context. The SDK has a `ContextsClient.setCurrent()` method, but this is more like `docker context use`--it does appear to change the global context.

Is there a way to set the context on specific requests, more like `--context`? If not can it be added?

**Comment by rumpl** [comment]
@bwateratmsft there is a way yes, you should set the context name in the metadata of the call, the key is [`context_key`](https://github.com/docker/compose-cli/blob/main/server/interceptor.go#L36). 

Example usage (built upon the `ps` [example](https://github.com/docker/node-sdk/blob/main/examples/ps.ts)):
```typescript
import * as grpc from '@grpc/grpc-js';

import { Containers } from '../src/index';
import { ListRequest, ListResponse } from '../src/containers';

const client = new Containers();
const metadata = new grpc.Metadata();
// Set the context for this call
metadata.add('context_key', 'my-context');

client.list(
  new ListRequest(),
  metadata,
  (error: grpc.ServiceError | null, response: ListResponse) => {
    if (error != null) {
      throw error;
    }
    const containers = response.getContainersList();
    containers.forEach((container) => {
      console.log(
        container.getId(),
        container.getImage(),
        container.getStatus()
      );
    });
  }
);
```

**Comment by bwateratmsft** [comment]
Awesome! This works, thanks @rumpl!
