### ISSUE TITLE
Containers.ListRequest does not return any containers deployed to Azure Container Instances

### ISSUE THREAD

**Issue by karolz-ms** [docker-archive-public/docker.node-sdk-legacy#67]
See https://github.com/microsoft/vscode-docker/issues/2941 for repro steps and result. I have debugged and [the getContainers() call](https://github.com/microsoft/vscode-docker/blob/main/src/docker/DockerServeClient/DockerServeClient.ts#L56) simply does not return anything.

I suspect we simply need a new release of the SDK--there have been changes tot the API/contracts, but they have never been released; the last release of the SDK is 7 months old (version 1.0.3).

BTW I am using Docker Desktop/Win version 3.3.3.

@gtardif @rumpl  FYI

**Comment by gtardif** [comment]
Hi @karolz-ms , sorry to get back late on this.

Just tried with latest VSCode & recent Desktop build, I can run ACI containers fine and see them in VSCode, updating live as expected. 
Also tried on mac a few days ago, I had some temporary ACI deployment failures on the backend, but the VSCode view was updating accordingly to reflect containers state.
Not sure what is different in our setup (running Desktop with not specific option, WSL2 VM, running commands from the windows host (not a WSL2 terminal). 

![aci_vscode_win](https://user-images.githubusercontent.com/437958/122572913-827a1f00-d04e-11eb-9f8b-97aff102fe96.png)

**Comment by karolz-ms** [comment]
Thank you @gtardif and sorry for not replying earlier. Going through a bit of a work deluge right now--I will try with latest bits and get back to you ASAP!

**Comment by karolz-ms** [comment]
I can still reproduce... 😞 

![image](https://user-images.githubusercontent.com/15271049/123336825-3ff78d00-d4fb-11eb-9de2-8eb5a26dcdcd.png)

This is using latest VS Code (1.57.1), latest Docker extension (1.14) and Docker Desktop (3.5 build 66024)

**Comment by karolz-ms** [comment]
@gtardif any hints how to debug further?

**Comment by bwateratmsft** [comment]
@gtardif any update? We're still seeing this issue 😞

**Comment by bwateratmsft** [comment]
I'm able to reproduce this still with Docker Desktop 4.0; I also tried fully logging out and back in with `docker login azure` and recreated the context; still no change.

**Comment by lorenrh** [comment]
Hello there! This issue was addressed in https://github.com/docker/compose-cli/pull/2088 and is now in Docker Desktop 4.2.0.

Would you mind verifying that the problem is actually fixed? 

Thanks in advance 😄

**Comment by bwateratmsft** [comment]
I tried today and it did not repro. It wasn't consistent when it did reproduce but you can close this issue; I'll reply back if I see it return.
